// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Member struct {
	ID    string   `json:"id"`
	Name  *string  `json:"name"`
	Skill []*Skill `json:"skill"`
}

type Params struct {
	Ids []string `json:"ids"`
}

type Skill struct {
	ID       string  `json:"id"`
	Category *string `json:"category"`
	Name     *string `json:"name"`
	Exp      *int    `json:"exp"`
}
